[package]
name = "leetcode-rs"
version = "0.1.0"
authors = ["haozibi <haozibi@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leetcode = { path = "./leetcode" }
anyhow = "1"
dialoguer = "0.7.1"